/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 brik.glb 
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Brik(props) {
  const {nodes, materials} = useGLTF('/brik.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.straight_122_buttons_v87.geometry}
        material={materials['Material.002']}
        position={[0.002, 0.726, -11.702]}
        rotation={[0, -1.571, 0]}
        scale={0.071}
        castShadow
      />
    </group>
  );
}

useGLTF.preload('/brik.glb');
