/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/brik.glb 
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Brik(props) {
  const {nodes, materials} = useGLTF('/brik.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['3MF_Object'].geometry}
        material={materials.BlackPlastic}
        position={[2.197, 0, -12.123]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.071, 0.072, 0.08]}
        castShadow
      />
    </group>
  );
}

useGLTF.preload('/brik.glb');
