/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/cube.glb 
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Cube(props) {
  const {nodes, materials} = useGLTF('/cube.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials['Material.001']}
        position={[-0.1, 31.89, 0]}
        scale={[86.892, 31.876, 86.892]}
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload('/cube.glb');
