/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/cylinder.glb 
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Cylinder(props) {
  const {nodes, materials} = useGLTF('/cylinder.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials['Material.001']}
        position={[0, 37.997, 0]}
        scale={[59.467, 37.976, 59.467]}
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload('/cylinder.glb');
