/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 flik.glb 
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Flik(props) {
  const {nodes, materials} = useGLTF('/flik.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['122_main_v310'].geometry}
        material={materials['Material.002']}
        position={[-0.207, 0.711, 11.494]}
        rotation={[0, 1.571, 0]}
        scale={0.071}
        castShadow
      />
    </group>
  );
}

useGLTF.preload('/flik.glb');
