/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/flik.glb 
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Flik(props) {
  const {nodes, materials} = useGLTF('/flik.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['3MF_Object001'].geometry}
        material={materials.BlackPlastic}
        position={[-1.632, 0, 11.651]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.071, 0.072, 0.073]}
        castShadow
      />
    </group>
  );
}

useGLTF.preload('/flik.glb');
