/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 pedestals.glb 
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Pedestals(props) {
  const {nodes, materials} = useGLTF('/pedestals.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['matte-black']}
        position={[0, -8.874, -12]}
        scale={[5.118, 8.854, 5.118]}
        receiveShadow
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials['matte-black']}
        position={[-12, -8.876, 0]}
        scale={[5.118, 8.854, 5.118]}
        receiveShadow
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials['matte-black']}
        position={[0, -8.876, 12]}
        scale={[5.118, 8.854, 5.118]}
        receiveShadow
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials['matte-black']}
        position={[12, -8.876, 0]}
        scale={[5.118, 8.854, 5.118]}
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload('/pedestals.glb');
