/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 room.glb 
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Room(props) {
  const {nodes, materials} = useGLTF('/room.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials['gloss-black']}
        position={[0, 23.987, 0]}
        scale={41.534}
      />
    </group>
  );
}

useGLTF.preload('/room.glb');
