/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/sleek.glb 
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Sleek(props) {
  const {nodes, materials} = useGLTF('/sleek.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['3MF_Object003'].geometry}
        material={materials.BlackPlastic}
        position={[-12.32, 0.023, -1.64]}
        scale={0.071}
        castShadow
      />
    </group>
  );
}

useGLTF.preload('/sleek.glb');
