/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 trak.glb 
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Trak(props) {
  const {nodes, materials} = useGLTF('/trak.glb');
  return (
    <group {...props} dispose={null}>
      <group
        position={[12.5, 0.692, -0.168]}
        rotation={[-Math.PI, 0.011, -Math.PI]}
        scale={0.071}
      >
        <mesh
          geometry={nodes.wide_straight_v22_1.geometry}
          material={materials.BlackPlastic}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload('/trak.glb');
